#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3

pipelines:
  tags:
    '**':
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - rm -rf tmp/wagon-git-e32cfaa675b19483ef204961ba3e3b46d3e315cd
          - git config --global user.email "sgoldstein@apache.org"
          - mvn -B deploy --file pom.xml 