[tool.poetry]
name = "service-manager"
version = "0.1.0"
description = "Serivce Manager is"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "src/main/python/service_manager"}]

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
strict=true