[tool.poetry]
name = "service-manager"
version = "0.1.0"
description = "Serivce Manager is"
authors = ["Scott Goldstein <sgoldstein@apache.org>"]
readme = "README.md"
packages = [{include = "src/main/python/service_manager"}]

[tool.poetry.dependencies]
python = "^3.12"
pylint = "^3.1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
strict=true

[tool.pytest.ini_options]
testpaths = [
    "src/test/python/**/*_test.py"
]
addopts = [
    "--import-mode=importlib",
]
pythonpath = [
    "src/main/python/service_manager",
    "src/test/python/service_manager"
]
