[tool.poetry]
name = "service_manager"
version = "0.2.0"
description = "Python implementation of a service manager framework"
authors = ["Scott Goldstein <sgoldstein@apache.org>"]
readme = "README.md"
packages = [{include = "src/main/python/service_manager"}]

[tool.poetry.dependencies]
python = "^3.12"
typing-extensions = "^4.11.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
coverage = {extras = ["toml"], version = "^7.4.4"}
pylint = "^3.1.0"
mypy = "^1.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
strict=true
mypy_path = [
    "src/main/python/service_manager",
    "src/test/python/service_manager"
]

[tool.pytest.ini_options]
testpaths = [
    "src/test/python/**/*_test.py"
]
addopts = [
    "--import-mode=importlib",
]
pythonpath = [
    "src/main/python/service_manager",
    "src/test/python/service_manager"
]

[tool.coverage.run]
include = ["src/*"]

[tool.coverage.report]
fail_under = 90
